### PR TITLE
Avoid unnecessary offscreen draws of repeating background map chunks

### PR DESCRIPTION
**Pull request by gamecubate**
Applied @Joncom's patch (per https://github.com/phoboslab/Impact/issues/11).

### CODE REVIEW

**Comment by Joncom** [comment]
This pull-request makes a lot of whitespace changes unrelated to the issue.

**Comment by gamecubate** [comment]
Strange. I had noticed some inconsistencies with spacing (tabs mixed w. spaces) but touched none of that. Will redo.

**Comment by Joncom** [comment]
Maybe your IDE is configured to trim whitespace in files on-save..

**Comment by gamecubate** [comment]
I try to avoid that in general. Will check my Atom settings.

**Comment by gamecubate** [comment]
Atom indeed. Disabled the whitespace package. All well now.

**Pull request closed without merging**
